# Generated by Django 4.1.4 on 2022-12-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='isFavorited',
            field=models.BooleanField(default=False, verbose_name='Favoritos'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HourService', related_query_name='HourService', to='api.hourservice', verbose_name='HourService'),
        ),
    ]
