# Generated by Django 4.1.4 on 2022-12-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_isfavorited_alter_schedule_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.CharField(max_length=5, verbose_name='Hora do Serviço'),
        ),
    ]
