# Generated by Django 4.1.4 on 2022-12-30 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_schedule_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Atualização')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Exclusão')),
                ('date', models.DateField(verbose_name='Data Abastecimento')),
                ('liter', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Litros')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('kilometer', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Kilometragem')),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Gasto')),
                ('total_liters', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Litros')),
            ],
            options={
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
            },
        ),
    ]
