# Generated by Django 4.1.4 on 2022-12-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_supply_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='kilometer',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Kilometragem'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='liter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Litros'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='total_expense',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Total Gasto'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='total_liters',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Total Litros'),
        ),
    ]
