# Generated by Django 4.1.4 on 2022-12-30 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_supply_kilometer_alter_supply_liter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='liter',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Litros'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Atualização')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Exclusão')),
                ('date', models.DateField(verbose_name='Data Manutenção')),
                ('name', models.CharField(max_length=50, verbose_name='Serviço')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
                ('start_kilometer', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Km Iníco')),
                ('end_kilometer', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Km Fim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance',
            },
        ),
    ]
