# Generated by Django 4.1.4 on 2022-12-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_supply_liter_alter_supply_price_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='name',
            field=models.CharField(choices=[('ÓLEO DE MOTOR', 'ÓLEO DE MOTOR'), ('FILTRO DE ÓLEO', 'FILTRO DE ÓLEO'), ('FILTRO AR CONDICIONA', 'FILTRO AR CONDICIONA'), ('FILTRO ÓLEO COMBUSTÍVEL', 'FILTRO ÓLEO COMBUSTÍVEL')], max_length=100, verbose_name='Tipo de Serviço'),
        ),
    ]
