# Generated by Django 4.1.4 on 2023-01-02 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_alter_maintenance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='name',
            field=models.CharField(choices=[('ÓLEO DE MOTOR', 'ÓLEO DE MOTOR'), ('FILTRO DE ÓLEO', 'FILTRO DE ÓLEO'), ('FILTRO AR CONDICIONA', 'FILTRO AR CONDICIONA'), ('FILTRO ÓLEO COMBUSTÍVEL', 'FILTRO ÓLEO COMBUSTÍVEL')], default='ÓLEO DE MOTOR', max_length=100, verbose_name='Tipo de Serviço'),
        ),
        migrations.CreateModel(
            name='Ipva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Atualização')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Exclusão')),
                ('date', models.DateField(verbose_name='Data Vencimento')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Ipva',
                'verbose_name_plural': 'Ipvas',
            },
        ),
    ]
