# Generated by Django 4.1.4 on 2023-01-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_calibratetire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='finetraffic',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da Multa'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='ipva',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='total_expense',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total Gasto'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='total_liters',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total Litros'),
        ),
    ]
