# Generated by Django 4.1.4 on 2023-01-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_service_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tipo de Serviço'),
        ),
    ]
