# Generated by Django 4.1.4 on 2023-01-06 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_insurance_agent_name_insurance_broker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '00 00 9 9999 9999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,20}$')], verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='policy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero Apolice:'),
        ),
    ]
