# Generated by Django 4.1.4 on 2023-01-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_insurance_phone_number_alter_insurance_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='due_date',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Data Vencimento'),
        ),
    ]
