# Generated by Django 4.1.4 on 2023-01-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_insurance_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finetraffic',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Data da Multa'),
        ),
        migrations.AlterField(
            model_name='finetraffic',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='finetraffic',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero da Multa'),
        ),
        migrations.AlterField(
            model_name='finetraffic',
            name='point',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Numero de Ponto'),
        ),
        migrations.AlterField(
            model_name='finetraffic',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço da Multa'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='due_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Data Vencimento'),
        ),
    ]
