# Generated by Django 4.1.4 on 2023-01-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_finetraffic_date_alter_finetraffic_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='liter',
            field=models.CharField(max_length=3, verbose_name='Litros'),
        ),
    ]
