# Generated by Django 4.1.4 on 2023-01-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_supply_liter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='liter',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
    ]
