# Generated by Django 4.1.4 on 2023-01-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_supply_liter_alter_supply_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='kilometer',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7, verbose_name='Kilometragem'),
        ),
    ]
