# Generated by Django 4.1.4 on 2023-01-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_calibratetire_libra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finetraffic',
            name='point',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Numero de Ponto'),
        ),
    ]
