from api.views.calibrateTireView import CalibrateTireModelViewSet
from api.views.fineTrafficView import FineTrafficModelViewSet
from api.views.insuranceView import InsuranceModelViewSet
from api.views.maintenanceView import MaintenanceModelViewSet
from api.views.supplyView import SupplyModelViewSet
from api.views.hourAvalibility import HourAvailibility
from api.views.hourServiceView import HourServiceModelViewSet
from api.views.userRegisterView import UserRegisterView
from api.views.addressView import AddressModelViewSet
from api.views.vehicleView import VehicleModelViewSet
from api.views.serviceView import ServiceModelViewSet
from api.views.scheduleView import ScheduleModelViewSet